name: Build Armbian for S905LB

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-armbian-s905lb.yml'  # 仅修改此文件时触发
  workflow_dispatch:  # 支持手动触发（推荐优先用手动触发测试）
  schedule:
    - cron: '0 2 * * *'  # 每日凌晨2点自动更新构建（可选）

jobs:
  build-s905lb:
    runs-on: ubuntu-22.04  # Armbian 构建推荐的稳定系统版本
    steps:
      1. 拉取 Armbian 官方构建脚本
      - name: Checkout Armbian Build Scripts
        uses: actions/checkout@v4
        with:
          repository: armbian/build  # 官方构建仓库（保证最新适配）
          path: armbian
          fetch-depth: 1  # 仅拉取最新代码，加快速度

      2. 安装构建依赖（官方推荐完整依赖集）
      - name: Install Required Dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y \
            build-essential debootstrap device-tree-compiler dosfstools f2fs-tools \
            flex gdisk git libelf-dev libssl-dev lz4 ncurses-dev parted pigz \
            python3 python3-pip rsync u-boot-tools unzip wget zstd

      3. 核心步骤：配置 S905LB 构建参数
      - name: Build Armbian for S905LB
        run: |
          cd armbian
          # 关键配置：BOARD=amlogic-s905（S905LB 通用适配型号）
          ./build.sh \
            BOARD=amlogic-s905 \          # ✅ 核心：S905LB 用此通用型号（无需改）
            BRANCH=current \              # 稳定分支（兼容新硬件，优先选）
            RELEASE=bookworm \            # 系统版本（Debian 12，稳定推荐）
            BUILD_MINIMAL=no \            # 构建完整系统（含基础工具，非最小化）
            BUILD_DESKTOP=no \            # 按需改 yes/no（yes 会生成带桌面的镜像）
            KERNEL_ONLY=no \              # 构建完整镜像（含内核+根文件系统）
            KERNEL_CONFIGURE=no \         # 不自定义内核配置（新手推荐）
            COMPRESS_OUTPUTIMAGE=sha,gpg  # 生成镜像校验文件（方便验证完整性）
            USERNAME=armbian \            # 默认用户名（可自定义，如 pi）
            PASSWORD=armbian \            # 默认密码（首次登录需修改）
            SERIALCON=uart0 \             # S905 系列默认串口（调试用，不影响日常）
            BUILD_ALL=yes                 # 生成所有格式镜像（img.xz 为主流）

      4. 上传构建产物（含镜像和内核头文件）
      - name: Upload Armbian Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: armbian-s905lb-output  # 产物包名称（便于识别）
          path: |
            armbian/output/images/*.img.xz  # 核心镜像文件（压缩格式，需解压后烧录）
            armbian/output/images/*.sha*    # 镜像校验文件（验证完整性）
            armbian/output/debs/linux-headers-*.deb  # ✅ 自动生成的内核头文件
          retention-days: 15  # 产物保留15天（避免占用仓库空间）
